sudo: required

language: python

python:
  - pypy
  - 2.6
  - 2.7
  - 3.4

# command to install dependencies
before_install:
  - sudo apt-get install libatlas-base-dev gfortran
  - pip install -r requirements.txt

install: ./setup.py build install
