sudo: false

language: python

cache:
  apt: true

addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev

python:
  - pypy
  - 2.6
  - 2.7

# command to install dependencies
before_install:
  - pip install -r requirements.txt

install: ./setup.py build install
