sudo: false

language: python

cache:
  apt: true

addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev

virtualenv:
    system_site_packages: true

python:
  - pypy
  - 2.6
  - 2.7

# command to install dependencies
before_install:
 - apt-get install python-numpy
 - apt-get install python-scipy
 - pip install -r requirements.txt

install: ./setup.py build install
