language: python

python:
  - pypy
  - 2.6
  - 2.7
  - 3.4

# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r requirements-test.txt --use-mirrors
    - python setup.py install

script:
    - python travistest.py
