sudo: required

language: python

cache:
  apt: true

addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev

# virtualenv:
#     system_site_packages: true

python:
  - 2.7

# command to install dependencies
before_install:
 - pip install -r requirements.txt

install: ./setup.py build install
