language: python

python:
  - pypy
  - 2.6
  - 2.7
  - 3.4

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - ./setup.py install
